DROP DATABASE IF EXISTS meeting;

CREATE DATABASE `meeting`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;


DROP DATABASE IF EXISTS meeting_test;

CREATE DATABASE `meeting_test`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;